In [3]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[9,8]])
print("Matrix Operations")
print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")

print("Matrix addition :\n",A + B)
print("Matrix Substraction :\n",B - A)
print("Matrix Multiplication :\n",np.dot(A,B))
print("Transpose :\n",A.T)

Matrix Operations
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [9 8]]
Matrix addition :
 [[ 6  8]
 [12 12]]
Matrix Substraction :
 [[4 4]
 [6 4]]
Matrix Multiplication :
 [[23 22]
 [51 50]]
Transpose :
 [[1 3]
 [2 4]]


In [1]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("original matrix:")
print(X)
print("\n reconstructed matrix(with  reduced dimensions):")
print(X_reconstructed)

original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 reconstructed matrix(with  reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
